### ISSUE TITLE
O_Clut.cube载入失败

### ISSUE THREAD

**Issue by SiriusHsh** [changyun233/Lumix-V-log-LUTs#1]
O_Clut.cube载入失败，这个lut确定可用吗？

**Comment by changyun233** [comment]
你好，BUG已修复，之前的LUT是65point的，超过了S5m2的限制，现在所有LUT都是33point的了，经测试后没有问题
修复commit：fix:orange_cyanlut now is 33 point

**Comment by changyun233** [comment]
感谢提出问题，欢迎将本仓库或Gitee 同名仓库https://gitee.com/changyun233/lumix-v-log-luts分享给更多松下用户
